// Code generated by fcgen; DO NOT EDIT.

package fc_tests

import (
	context "context"
	fmt "fmt"
	tests "github.com/metalfm/factory/internal/tests"
	atomic "sync/atomic"
)

type factoryArrayEmptyInterface struct {
	entity    *tests.ArrayEmptyInterface
	seq       func(e *tests.ArrayEmptyInterface)
	seqInt    func(e *tests.ArrayEmptyInterface)
	seqInt64  func(e *tests.ArrayEmptyInterface)
	onCreate  func(ctx context.Context, e *tests.ArrayEmptyInterface) error
	onArray0  func(e *tests.ArrayEmptyInterface)
	setArray0 bool
	onArray1  func(e *tests.ArrayEmptyInterface)
	setArray1 bool
	onArray2  func(e *tests.ArrayEmptyInterface)
	setArray2 bool
	onArray3  func(e *tests.ArrayEmptyInterface)
	setArray3 bool
	onArray4  func(e *tests.ArrayEmptyInterface)
	setArray4 bool
	onArray5  func(e *tests.ArrayEmptyInterface)
	setArray5 bool
}

func NewFactoryArrayEmptyInterface(e tests.ArrayEmptyInterface) *factoryArrayEmptyInterface {
	return &factoryArrayEmptyInterface{
		entity:   &e,
		seq:      func(e *tests.ArrayEmptyInterface) {},
		seqInt:   func(e *tests.ArrayEmptyInterface) {},
		seqInt64: func(e *tests.ArrayEmptyInterface) {},
		onCreate: func(ctx context.Context, e *tests.ArrayEmptyInterface) error { return nil },
		onArray0: func(e *tests.ArrayEmptyInterface) {},
		onArray1: func(e *tests.ArrayEmptyInterface) {},
		onArray2: func(e *tests.ArrayEmptyInterface) {},
		onArray3: func(e *tests.ArrayEmptyInterface) {},
		onArray4: func(e *tests.ArrayEmptyInterface) {},
		onArray5: func(e *tests.ArrayEmptyInterface) {},
	}
}

func (slf *factoryArrayEmptyInterface) Array0(v [5]interface{}) *factoryArrayEmptyInterface {
	slf.entity.Array0 = v
	slf.setArray0 = true
	return slf
}

func (slf *factoryArrayEmptyInterface) OnArray0(fn func(e *tests.ArrayEmptyInterface)) *factoryArrayEmptyInterface {
	slf.onArray0 = fn
	return slf
}

func (slf *factoryArrayEmptyInterface) Array1(v *[5]interface{}) *factoryArrayEmptyInterface {
	slf.entity.Array1 = v
	slf.setArray1 = true
	return slf
}

func (slf *factoryArrayEmptyInterface) OnArray1(fn func(e *tests.ArrayEmptyInterface)) *factoryArrayEmptyInterface {
	slf.onArray1 = fn
	return slf
}

func (slf *factoryArrayEmptyInterface) Array2(v *[5]*interface{}) *factoryArrayEmptyInterface {
	slf.entity.Array2 = v
	slf.setArray2 = true
	return slf
}

func (slf *factoryArrayEmptyInterface) OnArray2(fn func(e *tests.ArrayEmptyInterface)) *factoryArrayEmptyInterface {
	slf.onArray2 = fn
	return slf
}

func (slf *factoryArrayEmptyInterface) Array3(v [5]*interface{}) *factoryArrayEmptyInterface {
	slf.entity.Array3 = v
	slf.setArray3 = true
	return slf
}

func (slf *factoryArrayEmptyInterface) OnArray3(fn func(e *tests.ArrayEmptyInterface)) *factoryArrayEmptyInterface {
	slf.onArray3 = fn
	return slf
}

func (slf *factoryArrayEmptyInterface) Array4(v **[5]**interface{}) *factoryArrayEmptyInterface {
	slf.entity.Array4 = v
	slf.setArray4 = true
	return slf
}

func (slf *factoryArrayEmptyInterface) OnArray4(fn func(e *tests.ArrayEmptyInterface)) *factoryArrayEmptyInterface {
	slf.onArray4 = fn
	return slf
}

func (slf *factoryArrayEmptyInterface) Array5(v **[1][2]**interface{}) *factoryArrayEmptyInterface {
	slf.entity.Array5 = v
	slf.setArray5 = true
	return slf
}

func (slf *factoryArrayEmptyInterface) OnArray5(fn func(e *tests.ArrayEmptyInterface)) *factoryArrayEmptyInterface {
	slf.onArray5 = fn
	return slf
}

func (slf *factoryArrayEmptyInterface) Seq(fn func(e *tests.ArrayEmptyInterface)) *factoryArrayEmptyInterface {
	slf.seq = fn
	return slf
}

func (slf *factoryArrayEmptyInterface) SeqInt(fn func(e *tests.ArrayEmptyInterface, n int)) *factoryArrayEmptyInterface {
	var seq int32
	slf.seqInt = func(e *tests.ArrayEmptyInterface) {
		v := atomic.AddInt32(&seq, 1)
		fn(e, int(v))
	}
	return slf
}

func (slf *factoryArrayEmptyInterface) SeqInt64(fn func(e *tests.ArrayEmptyInterface, n int64)) *factoryArrayEmptyInterface {
	var seq int64
	slf.seqInt64 = func(e *tests.ArrayEmptyInterface) {
		v := atomic.AddInt64(&seq, 1)
		fn(e, v)
	}
	return slf
}

func (slf *factoryArrayEmptyInterface) OnCreate(fn func(ctx context.Context, e *tests.ArrayEmptyInterface) error) *factoryArrayEmptyInterface {
	slf.onCreate = fn
	return slf
}

func (slf *factoryArrayEmptyInterface) MustBuild() tests.ArrayEmptyInterface {
	return slf.MustBuildCtx(context.Background())
}

func (slf *factoryArrayEmptyInterface) MustBuildCtx(ctx context.Context) tests.ArrayEmptyInterface {
	slf.seq(slf.entity)
	slf.seqInt(slf.entity)
	slf.seqInt64(slf.entity)

	if !slf.setArray0 {
		slf.onArray0(slf.entity)
	}

	if !slf.setArray1 {
		slf.onArray1(slf.entity)
	}

	if !slf.setArray2 {
		slf.onArray2(slf.entity)
	}

	if !slf.setArray3 {
		slf.onArray3(slf.entity)
	}

	if !slf.setArray4 {
		slf.onArray4(slf.entity)
	}

	if !slf.setArray5 {
		slf.onArray5(slf.entity)
	}

	err := slf.onCreate(ctx, slf.entity)
	if err != nil {
		panic(fmt.Errorf("factory.OnCreate: %w", err))
	}

	return *slf.entity
}
