// Code generated by fcgen; DO NOT EDIT.

package fc_tests

import (
	context "context"
	tests "factory/internal/tests"
	fmt "fmt"
	atomic "sync/atomic"
)

type factoryChanUnExport struct {
	entity   *tests.ChanUnExport
	seq      func(e *tests.ChanUnExport)
	seqInt   func(e *tests.ChanUnExport)
	seqInt64 func(e *tests.ChanUnExport)
	onCreate func(ctx context.Context, e *tests.ChanUnExport) error
}

func NewFactoryChanUnExport(e tests.ChanUnExport) *factoryChanUnExport {
	return &factoryChanUnExport{
		entity:   &e,
		seq:      func(e *tests.ChanUnExport) {},
		seqInt:   func(e *tests.ChanUnExport) {},
		seqInt64: func(e *tests.ChanUnExport) {},
		onCreate: func(ctx context.Context, e *tests.ChanUnExport) error { return nil },
	}
}

func (slf *factoryChanUnExport) Seq(fn func(e *tests.ChanUnExport)) *factoryChanUnExport {
	slf.seq = fn
	return slf
}

func (slf *factoryChanUnExport) SeqInt(fn func(e *tests.ChanUnExport, n int)) *factoryChanUnExport {
	var seq int32
	slf.seqInt = func(e *tests.ChanUnExport) {
		v := atomic.AddInt32(&seq, 1)
		fn(e, int(v))
	}
	return slf
}

func (slf *factoryChanUnExport) SeqInt64(fn func(e *tests.ChanUnExport, n int64)) *factoryChanUnExport {
	var seq int64
	slf.seqInt64 = func(e *tests.ChanUnExport) {
		v := atomic.AddInt64(&seq, 1)
		fn(e, v)
	}
	return slf
}

func (slf *factoryChanUnExport) OnCreate(fn func(ctx context.Context, e *tests.ChanUnExport) error) *factoryChanUnExport {
	slf.onCreate = fn
	return slf
}

func (slf *factoryChanUnExport) MustBuild() tests.ChanUnExport {
	return slf.MustBuildCtx(context.Background())
}

func (slf *factoryChanUnExport) MustBuildCtx(ctx context.Context) tests.ChanUnExport {
	slf.seq(slf.entity)
	slf.seqInt(slf.entity)
	slf.seqInt64(slf.entity)

	err := slf.onCreate(ctx, slf.entity)
	if err != nil {
		panic(fmt.Errorf("factory.OnCreate: %w", err))
	}

	return *slf.entity
}
