// Code generated by fcgen; DO NOT EDIT.

package fc_tests

import (
	context "context"
	fmt "fmt"
	tests "github.com/metalfm/factory/internal/tests"
	atomic "sync/atomic"
)

type factoryObjUnExported struct {
	entity   *tests.ObjUnExported
	seq      func(e *tests.ObjUnExported)
	seqInt   func(e *tests.ObjUnExported)
	seqInt64 func(e *tests.ObjUnExported)
	onCreate func(ctx context.Context, e *tests.ObjUnExported) error
}

func NewFactoryObjUnExported(e tests.ObjUnExported) *factoryObjUnExported {
	return &factoryObjUnExported{
		entity:   &e,
		seq:      func(e *tests.ObjUnExported) {},
		seqInt:   func(e *tests.ObjUnExported) {},
		seqInt64: func(e *tests.ObjUnExported) {},
		onCreate: func(ctx context.Context, e *tests.ObjUnExported) error { return nil },
	}
}

func (slf *factoryObjUnExported) Seq(fn func(e *tests.ObjUnExported)) *factoryObjUnExported {
	slf.seq = fn
	return slf
}

func (slf *factoryObjUnExported) SeqInt(fn func(e *tests.ObjUnExported, n int)) *factoryObjUnExported {
	var seq int32
	slf.seqInt = func(e *tests.ObjUnExported) {
		v := atomic.AddInt32(&seq, 1)
		fn(e, int(v))
	}
	return slf
}

func (slf *factoryObjUnExported) SeqInt64(fn func(e *tests.ObjUnExported, n int64)) *factoryObjUnExported {
	var seq int64
	slf.seqInt64 = func(e *tests.ObjUnExported) {
		v := atomic.AddInt64(&seq, 1)
		fn(e, v)
	}
	return slf
}

func (slf *factoryObjUnExported) OnCreate(fn func(ctx context.Context, e *tests.ObjUnExported) error) *factoryObjUnExported {
	slf.onCreate = fn
	return slf
}

func (slf *factoryObjUnExported) MustBuild() tests.ObjUnExported {
	return slf.MustBuildCtx(context.Background())
}

func (slf *factoryObjUnExported) MustBuildCtx(ctx context.Context) tests.ObjUnExported {
	slf.seq(slf.entity)
	slf.seqInt(slf.entity)
	slf.seqInt64(slf.entity)

	err := slf.onCreate(ctx, slf.entity)
	if err != nil {
		panic(fmt.Errorf("factory.OnCreate: %w", err))
	}

	return *slf.entity
}
