// Code generated by fcgen; DO NOT EDIT.

package fc_tests

import (
	context "context"
	fmt "fmt"
	tests "github.com/metalfm/factory/internal/tests"
	atomic "sync/atomic"
	time1 "time"
)

type factorySelEmbedAlias struct {
	entity   *tests.SelEmbedAlias
	seq      func(e *tests.SelEmbedAlias)
	seqInt   func(e *tests.SelEmbedAlias)
	seqInt64 func(e *tests.SelEmbedAlias)
	onCreate func(ctx context.Context, e *tests.SelEmbedAlias) error
	onTime   func(e *tests.SelEmbedAlias)
	setTime  bool
}

func NewFactorySelEmbedAlias(e tests.SelEmbedAlias) *factorySelEmbedAlias {
	return &factorySelEmbedAlias{
		entity:   &e,
		seq:      func(e *tests.SelEmbedAlias) {},
		seqInt:   func(e *tests.SelEmbedAlias) {},
		seqInt64: func(e *tests.SelEmbedAlias) {},
		onCreate: func(ctx context.Context, e *tests.SelEmbedAlias) error { return nil },
		onTime:   func(e *tests.SelEmbedAlias) {},
	}
}

func (slf *factorySelEmbedAlias) Time(v time1.Time) *factorySelEmbedAlias {
	slf.entity.Time = v
	slf.setTime = true
	return slf
}

func (slf *factorySelEmbedAlias) OnTime(fn func(e *tests.SelEmbedAlias)) *factorySelEmbedAlias {
	slf.onTime = fn
	return slf
}

func (slf *factorySelEmbedAlias) Seq(fn func(e *tests.SelEmbedAlias)) *factorySelEmbedAlias {
	slf.seq = fn
	return slf
}

func (slf *factorySelEmbedAlias) SeqInt(fn func(e *tests.SelEmbedAlias, n int)) *factorySelEmbedAlias {
	var seq int32
	slf.seqInt = func(e *tests.SelEmbedAlias) {
		v := atomic.AddInt32(&seq, 1)
		fn(e, int(v))
	}
	return slf
}

func (slf *factorySelEmbedAlias) SeqInt64(fn func(e *tests.SelEmbedAlias, n int64)) *factorySelEmbedAlias {
	var seq int64
	slf.seqInt64 = func(e *tests.SelEmbedAlias) {
		v := atomic.AddInt64(&seq, 1)
		fn(e, v)
	}
	return slf
}

func (slf *factorySelEmbedAlias) OnCreate(fn func(ctx context.Context, e *tests.SelEmbedAlias) error) *factorySelEmbedAlias {
	slf.onCreate = fn
	return slf
}

func (slf *factorySelEmbedAlias) MustBuild() tests.SelEmbedAlias {
	return slf.MustBuildCtx(context.Background())
}

func (slf *factorySelEmbedAlias) MustBuildCtx(ctx context.Context) tests.SelEmbedAlias {
	slf.seq(slf.entity)
	slf.seqInt(slf.entity)
	slf.seqInt64(slf.entity)

	if !slf.setTime {
		slf.onTime(slf.entity)
	}

	err := slf.onCreate(ctx, slf.entity)
	if err != nil {
		panic(fmt.Errorf("factory.OnCreate: %w", err))
	}

	return *slf.entity
}
