// Code generated by fcgen; DO NOT EDIT.

package fc_tests

import (
	context "context"
	tests "factory/internal/tests"
	fmt "fmt"
	atomic "sync/atomic"
	time "time"
)

type factorySelEmbed struct {
	entity   *tests.SelEmbed
	seq      func(e *tests.SelEmbed)
	seqInt   func(e *tests.SelEmbed)
	seqInt64 func(e *tests.SelEmbed)
	onCreate func(ctx context.Context, e *tests.SelEmbed) error
	onTime   func(e *tests.SelEmbed)
	setTime  bool
}

func NewFactorySelEmbed(e tests.SelEmbed) *factorySelEmbed {
	return &factorySelEmbed{
		entity:   &e,
		seq:      func(e *tests.SelEmbed) {},
		seqInt:   func(e *tests.SelEmbed) {},
		seqInt64: func(e *tests.SelEmbed) {},
		onCreate: func(ctx context.Context, e *tests.SelEmbed) error { return nil },
		onTime:   func(e *tests.SelEmbed) {},
	}
}

func (slf *factorySelEmbed) Time(v time.Time) *factorySelEmbed {
	slf.entity.Time = v
	slf.setTime = true
	return slf
}

func (slf *factorySelEmbed) OnTime(fn func(e *tests.SelEmbed)) *factorySelEmbed {
	slf.onTime = fn
	return slf
}

func (slf *factorySelEmbed) Seq(fn func(e *tests.SelEmbed)) *factorySelEmbed {
	slf.seq = fn
	return slf
}

func (slf *factorySelEmbed) SeqInt(fn func(e *tests.SelEmbed, n int)) *factorySelEmbed {
	var seq int32
	slf.seqInt = func(e *tests.SelEmbed) {
		v := atomic.AddInt32(&seq, 1)
		fn(e, int(v))
	}
	return slf
}

func (slf *factorySelEmbed) SeqInt64(fn func(e *tests.SelEmbed, n int64)) *factorySelEmbed {
	var seq int64
	slf.seqInt64 = func(e *tests.SelEmbed) {
		v := atomic.AddInt64(&seq, 1)
		fn(e, v)
	}
	return slf
}

func (slf *factorySelEmbed) OnCreate(fn func(ctx context.Context, e *tests.SelEmbed) error) *factorySelEmbed {
	slf.onCreate = fn
	return slf
}

func (slf *factorySelEmbed) MustBuild() tests.SelEmbed {
	return slf.MustBuildCtx(context.Background())
}

func (slf *factorySelEmbed) MustBuildCtx(ctx context.Context) tests.SelEmbed {
	slf.seq(slf.entity)
	slf.seqInt(slf.entity)
	slf.seqInt64(slf.entity)

	if !slf.setTime {
		slf.onTime(slf.entity)
	}

	err := slf.onCreate(ctx, slf.entity)
	if err != nil {
		panic(fmt.Errorf("factory.OnCreate: %w", err))
	}

	return *slf.entity
}
