// Code generated by fcgen; DO NOT EDIT.

package fc_tests

import (
	context "context"
	tests "factory/internal/tests"
	fmt "fmt"
	atomic "sync/atomic"
)

type factoryTypesPointer struct {
	entity        *tests.TypesPointer
	seq           func(e *tests.TypesPointer)
	seqInt        func(e *tests.TypesPointer)
	seqInt64      func(e *tests.TypesPointer)
	onCreate      func(ctx context.Context, e *tests.TypesPointer) error
	onAny         func(e *tests.TypesPointer)
	setAny        bool
	onBool        func(e *tests.TypesPointer)
	setBool       bool
	onString      func(e *tests.TypesPointer)
	setString     bool
	onStr         func(e *tests.TypesPointer)
	setStr        bool
	onInt         func(e *tests.TypesPointer)
	setInt        bool
	onInt8        func(e *tests.TypesPointer)
	setInt8       bool
	onInt16       func(e *tests.TypesPointer)
	setInt16      bool
	onInt32       func(e *tests.TypesPointer)
	setInt32      bool
	onInt64       func(e *tests.TypesPointer)
	setInt64      bool
	onUint        func(e *tests.TypesPointer)
	setUint       bool
	onUint8       func(e *tests.TypesPointer)
	setUint8      bool
	onUint16      func(e *tests.TypesPointer)
	setUint16     bool
	onUint32      func(e *tests.TypesPointer)
	setUint32     bool
	onUint64      func(e *tests.TypesPointer)
	setUint64     bool
	onUintptr     func(e *tests.TypesPointer)
	setUintptr    bool
	onByte        func(e *tests.TypesPointer)
	setByte       bool
	onRune        func(e *tests.TypesPointer)
	setRune       bool
	onFloat32     func(e *tests.TypesPointer)
	setFloat32    bool
	onFloat64     func(e *tests.TypesPointer)
	setFloat64    bool
	onComplex64   func(e *tests.TypesPointer)
	setComplex64  bool
	onComplex128  func(e *tests.TypesPointer)
	setComplex128 bool
	onErr         func(e *tests.TypesPointer)
	setErr        bool
	onStr0        func(e *tests.TypesPointer)
	setStr0       bool
	onStr2        func(e *tests.TypesPointer)
	setStr2       bool
}

func NewFactoryTypesPointer(e tests.TypesPointer) *factoryTypesPointer {
	return &factoryTypesPointer{
		entity:       &e,
		seq:          func(e *tests.TypesPointer) {},
		seqInt:       func(e *tests.TypesPointer) {},
		seqInt64:     func(e *tests.TypesPointer) {},
		onCreate:     func(ctx context.Context, e *tests.TypesPointer) error { return nil },
		onAny:        func(e *tests.TypesPointer) {},
		onBool:       func(e *tests.TypesPointer) {},
		onString:     func(e *tests.TypesPointer) {},
		onStr:        func(e *tests.TypesPointer) {},
		onInt:        func(e *tests.TypesPointer) {},
		onInt8:       func(e *tests.TypesPointer) {},
		onInt16:      func(e *tests.TypesPointer) {},
		onInt32:      func(e *tests.TypesPointer) {},
		onInt64:      func(e *tests.TypesPointer) {},
		onUint:       func(e *tests.TypesPointer) {},
		onUint8:      func(e *tests.TypesPointer) {},
		onUint16:     func(e *tests.TypesPointer) {},
		onUint32:     func(e *tests.TypesPointer) {},
		onUint64:     func(e *tests.TypesPointer) {},
		onUintptr:    func(e *tests.TypesPointer) {},
		onByte:       func(e *tests.TypesPointer) {},
		onRune:       func(e *tests.TypesPointer) {},
		onFloat32:    func(e *tests.TypesPointer) {},
		onFloat64:    func(e *tests.TypesPointer) {},
		onComplex64:  func(e *tests.TypesPointer) {},
		onComplex128: func(e *tests.TypesPointer) {},
		onErr:        func(e *tests.TypesPointer) {},
		onStr0:       func(e *tests.TypesPointer) {},
		onStr2:       func(e *tests.TypesPointer) {},
	}
}

func (slf *factoryTypesPointer) Any(v *any) *factoryTypesPointer {
	slf.entity.Any = v
	slf.setAny = true
	return slf
}

func (slf *factoryTypesPointer) OnAny(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onAny = fn
	return slf
}

func (slf *factoryTypesPointer) Bool(v *bool) *factoryTypesPointer {
	slf.entity.Bool = v
	slf.setBool = true
	return slf
}

func (slf *factoryTypesPointer) OnBool(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onBool = fn
	return slf
}

func (slf *factoryTypesPointer) String(v *string) *factoryTypesPointer {
	slf.entity.String = v
	slf.setString = true
	return slf
}

func (slf *factoryTypesPointer) OnString(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onString = fn
	return slf
}

func (slf *factoryTypesPointer) Str(v ******string) *factoryTypesPointer {
	slf.entity.Str = v
	slf.setStr = true
	return slf
}

func (slf *factoryTypesPointer) OnStr(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onStr = fn
	return slf
}

func (slf *factoryTypesPointer) Int(v *int) *factoryTypesPointer {
	slf.entity.Int = v
	slf.setInt = true
	return slf
}

func (slf *factoryTypesPointer) OnInt(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onInt = fn
	return slf
}

func (slf *factoryTypesPointer) Int8(v *int8) *factoryTypesPointer {
	slf.entity.Int8 = v
	slf.setInt8 = true
	return slf
}

func (slf *factoryTypesPointer) OnInt8(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onInt8 = fn
	return slf
}

func (slf *factoryTypesPointer) Int16(v *int16) *factoryTypesPointer {
	slf.entity.Int16 = v
	slf.setInt16 = true
	return slf
}

func (slf *factoryTypesPointer) OnInt16(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onInt16 = fn
	return slf
}

func (slf *factoryTypesPointer) Int32(v *int32) *factoryTypesPointer {
	slf.entity.Int32 = v
	slf.setInt32 = true
	return slf
}

func (slf *factoryTypesPointer) OnInt32(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onInt32 = fn
	return slf
}

func (slf *factoryTypesPointer) Int64(v *int64) *factoryTypesPointer {
	slf.entity.Int64 = v
	slf.setInt64 = true
	return slf
}

func (slf *factoryTypesPointer) OnInt64(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onInt64 = fn
	return slf
}

func (slf *factoryTypesPointer) Uint(v *uint) *factoryTypesPointer {
	slf.entity.Uint = v
	slf.setUint = true
	return slf
}

func (slf *factoryTypesPointer) OnUint(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onUint = fn
	return slf
}

func (slf *factoryTypesPointer) Uint8(v *uint8) *factoryTypesPointer {
	slf.entity.Uint8 = v
	slf.setUint8 = true
	return slf
}

func (slf *factoryTypesPointer) OnUint8(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onUint8 = fn
	return slf
}

func (slf *factoryTypesPointer) Uint16(v *uint16) *factoryTypesPointer {
	slf.entity.Uint16 = v
	slf.setUint16 = true
	return slf
}

func (slf *factoryTypesPointer) OnUint16(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onUint16 = fn
	return slf
}

func (slf *factoryTypesPointer) Uint32(v *uint32) *factoryTypesPointer {
	slf.entity.Uint32 = v
	slf.setUint32 = true
	return slf
}

func (slf *factoryTypesPointer) OnUint32(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onUint32 = fn
	return slf
}

func (slf *factoryTypesPointer) Uint64(v *uint64) *factoryTypesPointer {
	slf.entity.Uint64 = v
	slf.setUint64 = true
	return slf
}

func (slf *factoryTypesPointer) OnUint64(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onUint64 = fn
	return slf
}

func (slf *factoryTypesPointer) Uintptr(v *uintptr) *factoryTypesPointer {
	slf.entity.Uintptr = v
	slf.setUintptr = true
	return slf
}

func (slf *factoryTypesPointer) OnUintptr(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onUintptr = fn
	return slf
}

func (slf *factoryTypesPointer) Byte(v *byte) *factoryTypesPointer {
	slf.entity.Byte = v
	slf.setByte = true
	return slf
}

func (slf *factoryTypesPointer) OnByte(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onByte = fn
	return slf
}

func (slf *factoryTypesPointer) Rune(v *rune) *factoryTypesPointer {
	slf.entity.Rune = v
	slf.setRune = true
	return slf
}

func (slf *factoryTypesPointer) OnRune(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onRune = fn
	return slf
}

func (slf *factoryTypesPointer) Float32(v *float32) *factoryTypesPointer {
	slf.entity.Float32 = v
	slf.setFloat32 = true
	return slf
}

func (slf *factoryTypesPointer) OnFloat32(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onFloat32 = fn
	return slf
}

func (slf *factoryTypesPointer) Float64(v *float64) *factoryTypesPointer {
	slf.entity.Float64 = v
	slf.setFloat64 = true
	return slf
}

func (slf *factoryTypesPointer) OnFloat64(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onFloat64 = fn
	return slf
}

func (slf *factoryTypesPointer) Complex64(v *complex64) *factoryTypesPointer {
	slf.entity.Complex64 = v
	slf.setComplex64 = true
	return slf
}

func (slf *factoryTypesPointer) OnComplex64(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onComplex64 = fn
	return slf
}

func (slf *factoryTypesPointer) Complex128(v *complex128) *factoryTypesPointer {
	slf.entity.Complex128 = v
	slf.setComplex128 = true
	return slf
}

func (slf *factoryTypesPointer) OnComplex128(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onComplex128 = fn
	return slf
}

func (slf *factoryTypesPointer) Err(v *error) *factoryTypesPointer {
	slf.entity.Err = v
	slf.setErr = true
	return slf
}

func (slf *factoryTypesPointer) OnErr(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onErr = fn
	return slf
}

func (slf *factoryTypesPointer) Str0(v *string) *factoryTypesPointer {
	slf.entity.Str0 = v
	slf.setStr0 = true
	return slf
}

func (slf *factoryTypesPointer) OnStr0(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onStr0 = fn
	return slf
}

func (slf *factoryTypesPointer) Str2(v *string) *factoryTypesPointer {
	slf.entity.Str2 = v
	slf.setStr2 = true
	return slf
}

func (slf *factoryTypesPointer) OnStr2(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.onStr2 = fn
	return slf
}

func (slf *factoryTypesPointer) Seq(fn func(e *tests.TypesPointer)) *factoryTypesPointer {
	slf.seq = fn
	return slf
}

func (slf *factoryTypesPointer) SeqInt(fn func(e *tests.TypesPointer, n int)) *factoryTypesPointer {
	var seq int32
	slf.seqInt = func(e *tests.TypesPointer) {
		v := atomic.AddInt32(&seq, 1)
		fn(e, int(v))
	}
	return slf
}

func (slf *factoryTypesPointer) SeqInt64(fn func(e *tests.TypesPointer, n int64)) *factoryTypesPointer {
	var seq int64
	slf.seqInt64 = func(e *tests.TypesPointer) {
		v := atomic.AddInt64(&seq, 1)
		fn(e, v)
	}
	return slf
}

func (slf *factoryTypesPointer) OnCreate(fn func(ctx context.Context, e *tests.TypesPointer) error) *factoryTypesPointer {
	slf.onCreate = fn
	return slf
}

func (slf *factoryTypesPointer) MustBuild() tests.TypesPointer {
	return slf.MustBuildCtx(context.Background())
}

func (slf *factoryTypesPointer) MustBuildCtx(ctx context.Context) tests.TypesPointer {
	slf.seq(slf.entity)
	slf.seqInt(slf.entity)
	slf.seqInt64(slf.entity)

	if !slf.setAny {
		slf.onAny(slf.entity)
	}

	if !slf.setBool {
		slf.onBool(slf.entity)
	}

	if !slf.setString {
		slf.onString(slf.entity)
	}

	if !slf.setStr {
		slf.onStr(slf.entity)
	}

	if !slf.setInt {
		slf.onInt(slf.entity)
	}

	if !slf.setInt8 {
		slf.onInt8(slf.entity)
	}

	if !slf.setInt16 {
		slf.onInt16(slf.entity)
	}

	if !slf.setInt32 {
		slf.onInt32(slf.entity)
	}

	if !slf.setInt64 {
		slf.onInt64(slf.entity)
	}

	if !slf.setUint {
		slf.onUint(slf.entity)
	}

	if !slf.setUint8 {
		slf.onUint8(slf.entity)
	}

	if !slf.setUint16 {
		slf.onUint16(slf.entity)
	}

	if !slf.setUint32 {
		slf.onUint32(slf.entity)
	}

	if !slf.setUint64 {
		slf.onUint64(slf.entity)
	}

	if !slf.setUintptr {
		slf.onUintptr(slf.entity)
	}

	if !slf.setByte {
		slf.onByte(slf.entity)
	}

	if !slf.setRune {
		slf.onRune(slf.entity)
	}

	if !slf.setFloat32 {
		slf.onFloat32(slf.entity)
	}

	if !slf.setFloat64 {
		slf.onFloat64(slf.entity)
	}

	if !slf.setComplex64 {
		slf.onComplex64(slf.entity)
	}

	if !slf.setComplex128 {
		slf.onComplex128(slf.entity)
	}

	if !slf.setErr {
		slf.onErr(slf.entity)
	}

	if !slf.setStr0 {
		slf.onStr0(slf.entity)
	}

	if !slf.setStr2 {
		slf.onStr2(slf.entity)
	}

	err := slf.onCreate(ctx, slf.entity)
	if err != nil {
		panic(fmt.Errorf("factory.OnCreate: %w", err))
	}

	return *slf.entity
}
