name: Generate
on:
  push:
    branches: [ '*' ]

permissions:
  contents: read

jobs:
  gen:
    strategy:
      matrix:
        go-version: [1.22.x, 1.23.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: make gen
      - name: if any modified files exists
        run: |
          if [ `git status --porcelain | wc -l` -gt 0 ]; then
            git --no-pager diff
            git --no-pager status -s
            exit 1
          fi
