name: Run tests
on:
  push:
    branches: ['*']

permissions:
  contents: read

jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.23.x, 1.24.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: make test
  gen:
    strategy:
      matrix:
        go-version: [ 1.23.x, 1.24.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: make gen
      - name: if any modified files exists
        run: |
          if [ `git status --porcelain | wc -l` -gt 0 ]; then
            git --no-pager diff
            git --no-pager status -s
            exit 1
          fi
  lint:
    strategy:
      matrix:
        go-version: [ 1.23.x, 1.24.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - run: make lint